spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5432/tendering_wf
    initialization-mode: always
